---
title: "Fig2"
author: "Dan Benesh"
date: "9/18/2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(ape)
library(RColorBrewer)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(stringsAsFactors = FALSE)
theme_set(new = theme_bw())
```

```{r}
hosts_per_stage <- read.csv(file = "../data/stage_level_combined.csv", header = TRUE)
```

```{r}
hosts_per_stage <- mutate(hosts_per_stage, di_plot = factor(Def.int, levels = c('int', 'def')))%>%
  mutate(di_plot = factor(di_plot, labels = c("intermediate", "definitive")))
```

# Host range

```{r}
f2u <- ggplot(filter(hosts_per_stage, Facultative != 'postcyclic'), # post-cyclic hosts removed
       aes(x = factor(Host.no), y = num_hosts_suspicious_removed, color = di_plot)) + 
  geom_boxplot(outlier.color = NA, color = 'black') +
  geom_point(alpha = 0.2, position = position_jitterdodge(jitter.width = 0.8, jitter.height = 0)) +
  scale_y_log10() +
  scale_color_brewer(type = "qual", palette = "Set2") +
  labs(x = "Stage (host) in life cycle", y = "Host records") +
  facet_grid(~lcl_max_fac, scales = 'free_x', space = 'free_x') + 
  theme(legend.title = element_blank(),
        legend.position = c(1,1),
        legend.justification = c(1,1),
        legend.background = element_rect(color = 'black'),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = 'grey95'),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank()) +
  guides(color = FALSE)
f2u
```

# Taxonomic dissimilarity index


```{r}
tax.ranks <- c('genus', 'family', 'order', 'class', 'phylum') # for axis label
```

The generalism of worms in second or third intermediate hosts is also clear when we split them by life cycle length. 

```{r}
f2l <- ggplot(filter(hosts_per_stage, Facultative != 'postcyclic'),
       aes(x = factor(Host.no), y = hsi_lcdb_suspcious_rem, color = di_plot)) + 
  geom_boxplot(outlier.color = NA, color = 'black') +
  geom_point(alpha = 0.2, position = position_jitterdodge(jitter.width = 0.8, jitter.height = 0)) +
  scale_y_continuous(limits = c(1,6), breaks = c(1:6), labels = c("species", tax.ranks)) +
  scale_color_brewer(type = "qual", palette = "Set2") +
  labs(x = "Stage (host) in life cycle", y = "Taxonomic dissimilarity") +
  facet_grid(~lcl_max_fac, scales = 'free_x', space = 'free_x') + 
  theme(legend.title = element_blank(),
        legend.position = c(0.98,0.98),
        legend.justification = c(1,1),
        legend.direction = 'horizontal',
        legend.background = element_rect(color = 'black'),
        legend.margin = margin(t=0.5, r=0.5, b = 0.5, l=0.5),
        legend.key = element_rect(fill = NA),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = 'grey95'),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank()) +
  guides(color = guide_legend(override.aes = list(alpha = 1)))
f2l
```

Combine the two figures

```{r}
library(cowplot)
```

```{r}
f2u2 <- f2u + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank())

f2l2 <- f2l +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank())
```

```{r}
ap <- align_plots(f2u2, f2l2, align="hv")
f2c <- gridExtra::grid.arrange(ap[[1]], ap[[2]])
```



Export as SVG and PNG, first Fig 1a...

```{r}
fig_width <- 7
fig_height <- 4

# ggsave(filename = "../figs/Fig2u.svg", plot = f2u, device = 'svg', units = 'in', width = fig_width, height = fig_height)
ggsave(filename = "../figs/Fig2u.png", plot = f2u, device = 'png', units = 'in', width = fig_width, height = fig_height)
```

...then Fig 1b.

```{r}
# ggsave(filename = "../figs/Fig2l.svg", plot = f2l, device = 'svg', units = 'in', width = fig_width, height = fig_height)
ggsave(filename = "../figs/Fig2l.png", plot = f2l, device = 'png', units = 'in', width = fig_width, height = fig_height)
```

Edit the combined figure by bringing the upper plot down, and make the legend more evenly spaced.

```{r}
ggsave(filename = "../figs/Fig2_comb.svg", plot = f2c, device = 'svg', units = "in", width = fig_width, height = fig_height*2)
```

